// WAVENOX Responsive Media Manifest
// Generated automatically by scripts/build-images.mjs. Do not edit manually.
import type { MediaDescriptor } from "@/components/system/Media";

export const media = {
  "home-hero": {
    src: "/media/home-hero-1600w.jpg",
    alt: "Contemporary residential villa in Jubilee Hills with low-profile flush-mounted monocrystalline solar array at golden hour",
    width: 1376,
    height: 768,
    avif: "/media/home-hero-640w.avif 640w, /media/home-hero-1080w.avif 1080w, /media/home-hero-1600w.avif 1600w, /media/home-hero-1920w.avif 1920w",
    webp: "/media/home-hero-640w.webp 640w, /media/home-hero-1080w.webp 1080w, /media/home-hero-1600w.webp 1600w, /media/home-hero-1920w.webp 1920w",
    mobileSrc: "/media/home-hero-mobile.jpg",
    mobileWebp: "/media/home-hero-mobile.webp",
    mobileAvif: "/media/home-hero-mobile.avif",
  } as MediaDescriptor,
  "home-design": {
    src: "/media/home-design-1600w.jpg",
    alt: "Architectural macro detail of concealed mounting structure and matte-black solar panels on rooftop terrace",
    width: 1376,
    height: 768,
    avif: "/media/home-design-640w.avif 640w, /media/home-design-1080w.avif 1080w, /media/home-design-1600w.avif 1600w, /media/home-design-1920w.avif 1920w",
    webp: "/media/home-design-640w.webp 640w, /media/home-design-1080w.webp 1080w, /media/home-design-1600w.webp 1600w, /media/home-design-1920w.webp 1920w",
    mobileSrc: "/media/home-design-mobile.jpg",
    mobileWebp: "/media/home-design-mobile.webp",
    mobileAvif: "/media/home-design-mobile.avif",
  } as MediaDescriptor,
  "home-outage": {
    src: "/media/home-outage-1600w.jpg",
    alt: "Cinematic dusk neighborhood during power outage with residential villa warmly illuminated by stored solar power",
    width: 1376,
    height: 768,
    avif: "/media/home-outage-640w.avif 640w, /media/home-outage-1080w.avif 1080w, /media/home-outage-1600w.avif 1600w, /media/home-outage-1920w.avif 1920w",
    webp: "/media/home-outage-640w.webp 640w, /media/home-outage-1080w.webp 1080w, /media/home-outage-1600w.webp 1600w, /media/home-outage-1920w.webp 1920w",
    mobileSrc: "/media/home-outage-mobile.jpg",
    mobileWebp: "/media/home-outage-mobile.webp",
    mobileAvif: "/media/home-outage-mobile.avif",
  } as MediaDescriptor,
  "home-heat": {
    src: "/media/home-heat-1600w.jpg",
    alt: "Studio macro shot of N-type TOPCon bifacial cell architecture under precision golden edge illumination",
    width: 1920,
    height: 1088,
    avif: "/media/home-heat-640w.avif 640w, /media/home-heat-1080w.avif 1080w, /media/home-heat-1600w.avif 1600w, /media/home-heat-1920w.avif 1920w",
    webp: "/media/home-heat-640w.webp 640w, /media/home-heat-1080w.webp 1080w, /media/home-heat-1600w.webp 1600w, /media/home-heat-1920w.webp 1920w",
    mobileSrc: "/media/home-heat-mobile.jpg",
    mobileWebp: "/media/home-heat-mobile.webp",
    mobileAvif: "/media/home-heat-mobile.avif",
  } as MediaDescriptor,
  "home-final": {
    src: "/media/home-final-1600w.jpg",
    alt: "Architectural residential terrace with elevated solar pergola living canopy at twilight",
    width: 1920,
    height: 1088,
    avif: "/media/home-final-640w.avif 640w, /media/home-final-1080w.avif 1080w, /media/home-final-1600w.avif 1600w, /media/home-final-1920w.avif 1920w",
    webp: "/media/home-final-640w.webp 640w, /media/home-final-1080w.webp 1080w, /media/home-final-1600w.webp 1600w, /media/home-final-1920w.webp 1920w",
    mobileSrc: "/media/home-final-mobile.jpg",
    mobileWebp: "/media/home-final-mobile.webp",
    mobileAvif: "/media/home-final-mobile.avif",
  } as MediaDescriptor,
  "res-hero": {
    src: "/media/res-hero-1600w.jpg",
    alt: "Contemporary villa residence with floor-to-ceiling glass and all-black solar array",
    width: 1376,
    height: 768,
    avif: "/media/res-hero-640w.avif 640w, /media/res-hero-1080w.avif 1080w, /media/res-hero-1600w.avif 1600w, /media/res-hero-1920w.avif 1920w",
    webp: "/media/res-hero-640w.webp 640w, /media/res-hero-1080w.webp 1080w, /media/res-hero-1600w.webp 1600w, /media/res-hero-1920w.webp 1920w",
    mobileSrc: "/media/res-hero-mobile.jpg",
    mobileWebp: "/media/res-hero-mobile.webp",
    mobileAvif: "/media/res-hero-mobile.avif",
  } as MediaDescriptor,
  "res-terrace": {
    src: "/media/res-terrace-1600w.jpg",
    alt: "Urban independent residence rooftop terrace featuring flush-mounted solar array and pristine usable area",
    width: 1920,
    height: 1088,
    avif: "/media/res-terrace-640w.avif 640w, /media/res-terrace-1080w.avif 1080w, /media/res-terrace-1600w.avif 1600w, /media/res-terrace-1920w.avif 1920w",
    webp: "/media/res-terrace-640w.webp 640w, /media/res-terrace-1080w.webp 1080w, /media/res-terrace-1600w.webp 1600w, /media/res-terrace-1920w.webp 1920w",
    mobileSrc: "/media/res-terrace-mobile.jpg",
    mobileWebp: "/media/res-terrace-mobile.webp",
    mobileAvif: "/media/res-terrace-mobile.avif",
  } as MediaDescriptor,
  "res-weather": {
    src: "/media/res-weather-1600w.jpg",
    alt: "Severe weather durability testing on anti-reflective hydrophobic tempered glass solar module",
    width: 1200,
    height: 1200,
    avif: "/media/res-weather-640w.avif 640w, /media/res-weather-1080w.avif 1080w, /media/res-weather-1600w.avif 1600w, /media/res-weather-1920w.avif 1920w",
    webp: "/media/res-weather-640w.webp 640w, /media/res-weather-1080w.webp 1080w, /media/res-weather-1600w.webp 1600w, /media/res-weather-1920w.webp 1920w",
    mobileSrc: "/media/res-weather-mobile.jpg",
    mobileWebp: "/media/res-weather-mobile.webp",
    mobileAvif: "/media/res-weather-mobile.avif",
  } as MediaDescriptor,
  "omnigrid-hero": {
    src: "/media/omnigrid-hero-1600w.jpg",
    alt: "Matte graphite home battery energy storage system mounted in garage utility room",
    width: 1440,
    height: 1440,
    avif: "/media/omnigrid-hero-640w.avif 640w, /media/omnigrid-hero-1080w.avif 1080w, /media/omnigrid-hero-1600w.avif 1600w, /media/omnigrid-hero-1920w.avif 1920w",
    webp: "/media/omnigrid-hero-640w.webp 640w, /media/omnigrid-hero-1080w.webp 1080w, /media/omnigrid-hero-1600w.webp 1600w, /media/omnigrid-hero-1920w.webp 1920w",
    mobileSrc: "/media/omnigrid-hero-mobile.jpg",
    mobileWebp: "/media/omnigrid-hero-mobile.webp",
    mobileAvif: "/media/omnigrid-hero-mobile.avif",
  } as MediaDescriptor,
  "omnigrid-switchover": {
    src: "/media/omnigrid-switchover-1600w.jpg",
    alt: "Solid-state microgrid transfer switchgear and high-speed telemetry pulse indicator",
    width: 1088,
    height: 1440,
    avif: "/media/omnigrid-switchover-640w.avif 640w, /media/omnigrid-switchover-1080w.avif 1080w, /media/omnigrid-switchover-1600w.avif 1600w, /media/omnigrid-switchover-1920w.avif 1920w",
    webp: "/media/omnigrid-switchover-640w.webp 640w, /media/omnigrid-switchover-1080w.webp 1080w, /media/omnigrid-switchover-1600w.webp 1600w, /media/omnigrid-switchover-1920w.webp 1920w",
    mobileSrc: "/media/omnigrid-switchover-mobile.jpg",
    mobileWebp: "/media/omnigrid-switchover-mobile.webp",
    mobileAvif: "/media/omnigrid-switchover-mobile.avif",
  } as MediaDescriptor,
  "omnigrid-night": {
    src: "/media/omnigrid-night-1600w.jpg",
    alt: "Modern luxury home living area illuminated seamlessly after sunset using daytime stored solar energy",
    width: 1920,
    height: 1088,
    avif: "/media/omnigrid-night-640w.avif 640w, /media/omnigrid-night-1080w.avif 1080w, /media/omnigrid-night-1600w.avif 1600w, /media/omnigrid-night-1920w.avif 1920w",
    webp: "/media/omnigrid-night-640w.webp 640w, /media/omnigrid-night-1080w.webp 1080w, /media/omnigrid-night-1600w.webp 1600w, /media/omnigrid-night-1920w.webp 1920w",
    mobileSrc: "/media/omnigrid-night-mobile.jpg",
    mobileWebp: "/media/omnigrid-night-mobile.webp",
    mobileAvif: "/media/omnigrid-night-mobile.avif",
  } as MediaDescriptor,
  "commercial-hero": {
    src: "/media/commercial-hero-1600w.jpg",
    alt: "2 MW commercial technology campus rooftop solar array at sunrise engineered for industrial load offset",
    width: 1376,
    height: 768,
    avif: "/media/commercial-hero-640w.avif 640w, /media/commercial-hero-1080w.avif 1080w, /media/commercial-hero-1600w.avif 1600w, /media/commercial-hero-1920w.avif 1920w",
    webp: "/media/commercial-hero-640w.webp 640w, /media/commercial-hero-1080w.webp 1080w, /media/commercial-hero-1600w.webp 1600w, /media/commercial-hero-1920w.webp 1920w",
    mobileSrc: "/media/commercial-hero-mobile.jpg",
    mobileWebp: "/media/commercial-hero-mobile.webp",
    mobileAvif: "/media/commercial-hero-mobile.avif",
  } as MediaDescriptor,
  "commercial-industrial": {
    src: "/media/commercial-industrial-1600w.jpg",
    alt: "Heavy manufacturing and pharmaceutical facility rooftop equipped with high-yield bifacial solar panels",
    width: 1920,
    height: 1088,
    avif: "/media/commercial-industrial-640w.avif 640w, /media/commercial-industrial-1080w.avif 1080w, /media/commercial-industrial-1600w.avif 1600w, /media/commercial-industrial-1920w.avif 1920w",
    webp: "/media/commercial-industrial-640w.webp 640w, /media/commercial-industrial-1080w.webp 1080w, /media/commercial-industrial-1600w.webp 1600w, /media/commercial-industrial-1920w.webp 1920w",
    mobileSrc: "/media/commercial-industrial-mobile.jpg",
    mobileWebp: "/media/commercial-industrial-mobile.webp",
    mobileAvif: "/media/commercial-industrial-mobile.avif",
  } as MediaDescriptor,
  "commercial-campus": {
    src: "/media/commercial-campus-1600w.jpg",
    alt: "Contemporary corporate headquarters atrium overlooking an expansive clean-energy rooftop solar microgrid",
    width: 1024,
    height: 1024,
    avif: "/media/commercial-campus-640w.avif 640w, /media/commercial-campus-1080w.avif 1080w, /media/commercial-campus-1600w.avif 1600w, /media/commercial-campus-1920w.avif 1920w",
    webp: "/media/commercial-campus-640w.webp 640w, /media/commercial-campus-1080w.webp 1080w, /media/commercial-campus-1600w.webp 1600w, /media/commercial-campus-1920w.webp 1920w",
    mobileSrc: "/media/commercial-campus-mobile.jpg",
    mobileWebp: "/media/commercial-campus-mobile.webp",
    mobileAvif: "/media/commercial-campus-mobile.avif",
  } as MediaDescriptor,
  "studio-estate": {
    src: "/media/studio-estate-1600w.jpg",
    alt: "Architectural 3D CAD multi-roof estate layout model engineered for comprehensive solar generation",
    width: 1440,
    height: 1440,
    avif: "/media/studio-estate-640w.avif 640w, /media/studio-estate-1080w.avif 1080w, /media/studio-estate-1600w.avif 1600w, /media/studio-estate-1920w.avif 1920w",
    webp: "/media/studio-estate-640w.webp 640w, /media/studio-estate-1080w.webp 1080w, /media/studio-estate-1600w.webp 1600w, /media/studio-estate-1920w.webp 1920w",
    mobileSrc: "/media/studio-estate-mobile.jpg",
    mobileWebp: "/media/studio-estate-mobile.webp",
    mobileAvif: "/media/studio-estate-mobile.avif",
  } as MediaDescriptor,
  "liquid-glass": {
    src: "/media/liquid-glass-1600w.jpg",
    alt: "Liquid anti-reflective tempered glass coating reflecting sky and capturing oblique sun rays",
    width: 1376,
    height: 768,
    avif: "/media/liquid-glass-640w.avif 640w, /media/liquid-glass-1080w.avif 1080w, /media/liquid-glass-1600w.avif 1600w, /media/liquid-glass-1920w.avif 1920w",
    webp: "/media/liquid-glass-640w.webp 640w, /media/liquid-glass-1080w.webp 1080w, /media/liquid-glass-1600w.webp 1600w, /media/liquid-glass-1920w.webp 1920w",
    mobileSrc: "/media/liquid-glass-mobile.jpg",
    mobileWebp: "/media/liquid-glass-mobile.webp",
    mobileAvif: "/media/liquid-glass-mobile.avif",
  } as MediaDescriptor,
  "homes-hero": {
    src: "/media/res-hero-1600w.jpg",
    alt: "Contemporary villa residence with floor-to-ceiling glass and clean all-black solar array",
    width: 1376,
    height: 768,
    avif: "/media/res-hero-640w.avif 640w, /media/res-hero-1080w.avif 1080w, /media/res-hero-1600w.avif 1600w, /media/res-hero-1920w.avif 1920w",
    webp: "/media/res-hero-640w.webp 640w, /media/res-hero-1080w.webp 1080w, /media/res-hero-1600w.webp 1600w, /media/res-hero-1920w.webp 1920w",
    mobileSrc: "/media/res-hero-mobile.jpg",
    mobileWebp: "/media/res-hero-mobile.webp",
    mobileAvif: "/media/res-hero-mobile.avif",
  } as MediaDescriptor,
} as const;

export type MediaKey = keyof typeof media;
