// WAVENOX Responsive Media Manifest
// Generated automatically by scripts/build-images.mjs. Do not edit manually.
import type { MediaDescriptor } from "@/components/system/Media";

export const media = {
  "home-hero": {
    src: "/media/home-hero-1600w.jpg",
    alt: "Contemporary residential villa with low-profile monocrystalline solar panels on flat terrace roof",
    width: 1376,
    height: 768,
    avif: "/media/home-hero-640w.avif 640w, /media/home-hero-1080w.avif 1080w",
    webp: "/media/home-hero-640w.webp 640w, /media/home-hero-1080w.webp 1080w",
    mobileSrc: "/media/home-hero-mobile.jpg",
    mobileWebp: "/media/home-hero-mobile.webp",
    mobileAvif: "/media/home-hero-mobile.avif",
  } as MediaDescriptor,
  "home-design": {
    src: "/media/home-design-1600w.jpg",
    alt: "Concealed mounting structure and seamless black solar panels integrated into rooftop terrace",
    width: 1200,
    height: 1200,
    avif: "/media/home-design-640w.avif 640w, /media/home-design-1080w.avif 1080w",
    webp: "/media/home-design-640w.webp 640w, /media/home-design-1080w.webp 1080w",
    mobileSrc: "/media/home-design-mobile.jpg",
    mobileWebp: "/media/home-design-mobile.webp",
    mobileAvif: "/media/home-design-mobile.avif",
  } as MediaDescriptor,
  "home-outage": {
    src: "/media/home-outage-1600w.jpg",
    alt: "Warmly illuminated residential home powered by Omnigrid battery storage during an evening grid disruption",
    width: 1440,
    height: 1440,
    avif: "/media/home-outage-640w.avif 640w, /media/home-outage-1080w.avif 1080w",
    webp: "/media/home-outage-640w.webp 640w, /media/home-outage-1080w.webp 1080w",
    mobileSrc: "/media/home-outage-mobile.jpg",
    mobileWebp: "/media/home-outage-mobile.webp",
    mobileAvif: "/media/home-outage-mobile.avif",
  } as MediaDescriptor,
  "home-heat": {
    src: "/media/home-heat-1600w.jpg",
    alt: "High-efficiency N-type TOPCon bifacial solar cells capturing midday sunlight in extreme temperatures",
    width: 1024,
    height: 1024,
    avif: "/media/home-heat-640w.avif 640w",
    webp: "/media/home-heat-640w.webp 640w",
    mobileSrc: "/media/home-heat-mobile.jpg",
    mobileWebp: "/media/home-heat-mobile.webp",
    mobileAvif: "/media/home-heat-mobile.avif",
  } as MediaDescriptor,
  "home-final": {
    src: "/media/home-final-1600w.jpg",
    alt: "Architectural residential terrace with elevated solar pergola living canopy at twilight",
    width: 1920,
    height: 1088,
    avif: "/media/home-final-640w.avif 640w, /media/home-final-1080w.avif 1080w, /media/home-final-1600w.avif 1600w",
    webp: "/media/home-final-640w.webp 640w, /media/home-final-1080w.webp 1080w, /media/home-final-1600w.webp 1600w",
    mobileSrc: "/media/home-final-mobile.jpg",
    mobileWebp: "/media/home-final-mobile.webp",
    mobileAvif: "/media/home-final-mobile.avif",
  } as MediaDescriptor,
  "omnigrid-hero": {
    src: "/media/omnigrid-hero-1600w.jpg",
    alt: "Omnigrid home battery energy storage system mounted cleanly on garage wall with live telemetry indicator",
    width: 1440,
    height: 1440,
    avif: "/media/omnigrid-hero-640w.avif 640w, /media/omnigrid-hero-1080w.avif 1080w",
    webp: "/media/omnigrid-hero-640w.webp 640w, /media/omnigrid-hero-1080w.webp 1080w",
    mobileSrc: "/media/omnigrid-hero-mobile.jpg",
    mobileWebp: "/media/omnigrid-hero-mobile.webp",
    mobileAvif: "/media/omnigrid-hero-mobile.avif",
  } as MediaDescriptor,
  "homes-hero": {
    src: "/media/homes-hero-1600w.jpg",
    alt: "Urban independent home with complete turnkey residential rooftop solar installation",
    width: 1920,
    height: 1088,
    avif: "/media/homes-hero-640w.avif 640w, /media/homes-hero-1080w.avif 1080w, /media/homes-hero-1600w.avif 1600w",
    webp: "/media/homes-hero-640w.webp 640w, /media/homes-hero-1080w.webp 1080w, /media/homes-hero-1600w.webp 1600w",
    mobileSrc: "/media/homes-hero-mobile.jpg",
    mobileWebp: "/media/homes-hero-mobile.webp",
    mobileAvif: "/media/homes-hero-mobile.avif",
  } as MediaDescriptor,
  "commercial-hero": {
    src: "/media/commercial-hero-1600w.jpg",
    alt: "Multi-megawatt industrial manufacturing facility rooftop solar array engineered for heavy load offset",
    width: 1376,
    height: 768,
    avif: "/media/commercial-hero-640w.avif 640w, /media/commercial-hero-1080w.avif 1080w",
    webp: "/media/commercial-hero-640w.webp 640w, /media/commercial-hero-1080w.webp 1080w",
    mobileSrc: "/media/commercial-hero-mobile.jpg",
    mobileWebp: "/media/commercial-hero-mobile.webp",
    mobileAvif: "/media/commercial-hero-mobile.avif",
  } as MediaDescriptor,
} as const;

export type MediaKey = keyof typeof media;
