/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiquidGlassRouteImport } from './routes/liquid-glass'
import { Route as IndexRouteImport } from './routes/index'

const LiquidGlassRoute = LiquidGlassRouteImport.update({
  id: '/liquid-glass',
  path: '/liquid-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/liquid-glass': typeof LiquidGlassRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/liquid-glass': typeof LiquidGlassRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/liquid-glass': typeof LiquidGlassRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/liquid-glass'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/liquid-glass'
  id: '__root__' | '/' | '/liquid-glass'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiquidGlassRoute: typeof LiquidGlassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/liquid-glass': {
      id: '/liquid-glass'
      path: '/liquid-glass'
      fullPath: '/liquid-glass'
      preLoaderRoute: typeof LiquidGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiquidGlassRoute: LiquidGlassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
