/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutThisProjectRouteImport } from './routes/about-this-project'
import { Route as ArchitectsRouteImport } from './routes/architects'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as NetMeteringRouteImport } from './routes/net-metering'
import { Route as OmnigridRouteImport } from './routes/omnigrid'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ResidentialRouteImport } from './routes/residential'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as LegalDisclosuresRouteImport } from './routes/legal/disclosures'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as OrderReceivedRouteImport } from './routes/order/received'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutThisProjectRoute = AboutThisProjectRouteImport.update({
  id: '/about-this-project',
  path: '/about-this-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectsRoute = ArchitectsRouteImport.update({
  id: '/architects',
  path: '/architects',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const NetMeteringRoute = NetMeteringRouteImport.update({
  id: '/net-metering',
  path: '/net-metering',
  getParentRoute: () => rootRouteImport,
} as any)
const OmnigridRoute = OmnigridRouteImport.update({
  id: '/omnigrid',
  path: '/omnigrid',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialRoute = ResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclosuresRoute = LegalDisclosuresRouteImport.update({
  id: '/legal/disclosures',
  path: '/legal/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderReceivedRoute = OrderReceivedRouteImport.update({
  id: '/order/received',
  path: '/order/received',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-this-project': typeof AboutThisProjectRoute
  '/architects': typeof ArchitectsRoute
  '/deploy': typeof DeployRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/net-metering': typeof NetMeteringRoute
  '/omnigrid': typeof OmnigridRoute
  '/our-story': typeof OurStoryRoute
  '/residential': typeof ResidentialRoute
  '/service-areas': typeof ServiceAreasRoute
  '/technology': typeof TechnologyRoute
  '/warranty': typeof WarrantyRoute
  '/legal/disclosures': typeof LegalDisclosuresRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/received': typeof OrderReceivedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-this-project': typeof AboutThisProjectRoute
  '/architects': typeof ArchitectsRoute
  '/deploy': typeof DeployRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/net-metering': typeof NetMeteringRoute
  '/omnigrid': typeof OmnigridRoute
  '/our-story': typeof OurStoryRoute
  '/residential': typeof ResidentialRoute
  '/service-areas': typeof ServiceAreasRoute
  '/technology': typeof TechnologyRoute
  '/warranty': typeof WarrantyRoute
  '/legal/disclosures': typeof LegalDisclosuresRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/received': typeof OrderReceivedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-this-project': typeof AboutThisProjectRoute
  '/architects': typeof ArchitectsRoute
  '/deploy': typeof DeployRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/net-metering': typeof NetMeteringRoute
  '/omnigrid': typeof OmnigridRoute
  '/our-story': typeof OurStoryRoute
  '/residential': typeof ResidentialRoute
  '/service-areas': typeof ServiceAreasRoute
  '/technology': typeof TechnologyRoute
  '/warranty': typeof WarrantyRoute
  '/legal/disclosures': typeof LegalDisclosuresRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/received': typeof OrderReceivedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-this-project'
    | '/architects'
    | '/deploy'
    | '/enterprise'
    | '/faq'
    | '/net-metering'
    | '/omnigrid'
    | '/our-story'
    | '/residential'
    | '/service-areas'
    | '/technology'
    | '/warranty'
    | '/legal/disclosures'
    | '/legal/privacy'
    | '/legal/terms'
    | '/order/received'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-this-project'
    | '/architects'
    | '/deploy'
    | '/enterprise'
    | '/faq'
    | '/net-metering'
    | '/omnigrid'
    | '/our-story'
    | '/residential'
    | '/service-areas'
    | '/technology'
    | '/warranty'
    | '/legal/disclosures'
    | '/legal/privacy'
    | '/legal/terms'
    | '/order/received'
  id:
    | '__root__'
    | '/'
    | '/about-this-project'
    | '/architects'
    | '/deploy'
    | '/enterprise'
    | '/faq'
    | '/net-metering'
    | '/omnigrid'
    | '/our-story'
    | '/residential'
    | '/service-areas'
    | '/technology'
    | '/warranty'
    | '/legal/disclosures'
    | '/legal/privacy'
    | '/legal/terms'
    | '/order/received'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutThisProjectRoute: typeof AboutThisProjectRoute
  ArchitectsRoute: typeof ArchitectsRoute
  DeployRoute: typeof DeployRoute
  EnterpriseRoute: typeof EnterpriseRoute
  FaqRoute: typeof FaqRoute
  NetMeteringRoute: typeof NetMeteringRoute
  OmnigridRoute: typeof OmnigridRoute
  OurStoryRoute: typeof OurStoryRoute
  ResidentialRoute: typeof ResidentialRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  TechnologyRoute: typeof TechnologyRoute
  WarrantyRoute: typeof WarrantyRoute
  LegalDisclosuresRoute: typeof LegalDisclosuresRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  OrderReceivedRoute: typeof OrderReceivedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-this-project': {
      id: '/about-this-project'
      path: '/about-this-project'
      fullPath: '/about-this-project'
      preLoaderRoute: typeof AboutThisProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architects': {
      id: '/architects'
      path: '/architects'
      fullPath: '/architects'
      preLoaderRoute: typeof ArchitectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-metering': {
      id: '/net-metering'
      path: '/net-metering'
      fullPath: '/net-metering'
      preLoaderRoute: typeof NetMeteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omnigrid': {
      id: '/omnigrid'
      path: '/omnigrid'
      fullPath: '/omnigrid'
      preLoaderRoute: typeof OmnigridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential': {
      id: '/residential'
      path: '/residential'
      fullPath: '/residential'
      preLoaderRoute: typeof ResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclosures': {
      id: '/legal/disclosures'
      path: '/legal/disclosures'
      fullPath: '/legal/disclosures'
      preLoaderRoute: typeof LegalDisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/received': {
      id: '/order/received'
      path: '/order/received'
      fullPath: '/order/received'
      preLoaderRoute: typeof OrderReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutThisProjectRoute: AboutThisProjectRoute,
  ArchitectsRoute: ArchitectsRoute,
  DeployRoute: DeployRoute,
  EnterpriseRoute: EnterpriseRoute,
  FaqRoute: FaqRoute,
  NetMeteringRoute: NetMeteringRoute,
  OmnigridRoute: OmnigridRoute,
  OurStoryRoute: OurStoryRoute,
  ResidentialRoute: ResidentialRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  TechnologyRoute: TechnologyRoute,
  WarrantyRoute: WarrantyRoute,
  LegalDisclosuresRoute: LegalDisclosuresRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  OrderReceivedRoute: OrderReceivedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
